### ISSUE TITLE
Use `--no-install-recommends` with apt-get

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-chrome-for-testing#17]
By default APT installs not only required packages, but "recommended" packages too.

When we use apt-get in the base-image creation and also in the APT buildpack, we always pass `--no-install-recommends` when installing packages, to try and reduce image/slug size.

Currently this buildpack does not do that:
https://github.com/heroku/heroku-buildpack-chrome-for-testing/blob/10cb812caa6e1b0dc08ddd0b23377869a5a8f7d8/bin/install-chrome-dependencies#L88-L104

Now that the tests have been made more robust in #15 (they use `ldd` to check for missing dynamic libraries, and also fully launch chrome in both new and old headless modes), it will be much safer to try using `--no-install-recommends` in this buildpack to reduce slug size.

**Comment by Petercopter** [comment]
With this buildpack, `heroku/ruby` and `heroku/nodejs`, my slug is 364 megs. That's over the Heroku soft limit, so anything to reduce slug size would be great.
