### ISSUE TITLE
Cache isn't invalidated when the stack changes

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-chrome-for-testing#19]
From code inspection I can see the buildpack doesn't invalidate the cache when `$STACK` changes:
https://github.com/heroku/heroku-buildpack-chrome-for-testing/blob/10cb812caa6e1b0dc08ddd0b23377869a5a8f7d8/bin/install-chrome-dependencies

Compare to the APT buildpack which does invalidate when the cache changes:
https://github.com/heroku/heroku-buildpack-apt/blob/4eb4b35d35d0178e5cef73d6998a26ba2c9bbf17/bin/compile#L42-L86

The lack of invalidation causes errors like:

```
$ mkdir chrome-test && cd $_
$ git init && touch foo && git add -A && git commit -m '.'
$ heroku create --buildpack heroku-community/chrome-for-testing --stack heroku-22
$ git push heroku main
$ heroku stack:set heroku-20
$ git commit -am '.' --allow-empty && git push heroku main
$ h run chrome --version
Running chrome --version on ⬢ vast-forest-17664... up, run.6700 (Basic)
chrome: error while loading shared libraries: libffi.so.8: cannot open shared object file: No such file or directory
```

**Comment by Petercopter** [comment]
I think I encountered this. When I switched from the Google Chrome buildpack to this one, my slug was too large. Clearing the cache and redeploying brought it down and I was able to deploy.
