### ISSUE TITLE
Does heroku tolerate webscraping on yahoo finance?

### ISSUE THREAD

**Issue by Ludo915** [heroku/heroku-buildpack-chrome-for-testing#30]
Hi @mars,

I have a similar problem as the previous reported issue also with heroku, I removed the older chromedriver and and chrome buildpacks and added the buildpack https://github.com/heroku/heroku-buildpack-chrome-for-testing to my app and I get the following error:

![image](https://github.com/user-attachments/assets/eb412a02-0929-4330-81aa-0c1aa28163e7)

Can you please help?

_Originally posted by @Ludo915 in https://github.com/heroku/heroku-buildpack-chrome-for-testing/issues/29#issuecomment-2464037853_

**Comment by Ludo915** [comment]
[Heroku Build Log.txt](https://github.com/user-attachments/files/17681684/Heroku.Build.Log.txt)

`from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException, ElementClickInterceptedException

chrome_options = Options()
chrome_options.add_argument("--log-level=3")  # Only ERROR logs for Chrome
chrome_options.add_argument("--disable-logging")  # Disable Chrome logging entirely
chrome_options.add_argument("--headless")  # Run in headless mode
chrome_options.add_argument("--disable-gpu")  # Necessary on some environments
chrome_options.add_argument("--no-sandbox")  # Recommended for Heroku
chrome_options.add_argument("--disable-dev-shm-usage")  # Prevents errors in limited resources
chrome_options.add_argument('--ignore-certificate-errors')
chrome_options.add_argument('--ignore-ssl-errors')

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)
`

**Comment by mars** [comment]
Looks like that code calls `ChromeDriverManager().install()`, which sounds like it installs Chromedriver.

**Comment by Ludo915** [comment]
Hi @mars thanks for your assistance, what else would be relevant?

**Comment by mars** [comment]
That's it @Ludo915 … it seems like you'll need to change that configuration code to no longer call `ChromeDriverManager().install()`.

**Comment by Ludo915** [comment]
I understand but should I use something like the chrome_driver_path? If yes what should it be? Where do I get the information?:

```
driver = webdriver.Chrome(service=ChromeService(executable_path=chrome_driver_path), options=chrome_options)
```

**Comment by mars** [comment]
According to the [Python Selenium documentation](https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.chrome.webdriver), it looks like the `ChromeService` will default to use the `chromedriver` executable installed by this Chrome for Testing buildpack.

So, I'm guessing this is the solution, to not pass any args in `ChromeService()`:

```python
driver = webdriver.Chrome(service=ChromeService(), options=chrome_options)
```

I don't use Python though, so this is only a suggestion based on a quick look at the docs.

**Comment by mars** [comment]
Or maybe even just:
```python
driver = webdriver.Chrome(options=chrome_options)
```

**Comment by Ludo915** [comment]
Hi @mars and thank you, but now I get an error when I try to connect to yahoo finance, do you think it's because heroku prohibits webscraping on yahoo finance?

![image](https://github.com/user-attachments/assets/3b21c005-24f9-4508-b4c2-cf411b11d683)

**Comment by mars** [comment]
Heroku is not going to block such an application, but likely Yahoo does block it. And using Heroku in this way is likely against the terms of service.

I cannot really comment further, and will be resetting this to you're original issue, which seems to have been solved, so that other people can learn from it. (Generally, please open new issues for different topics; don't rename/repurpose old ones).
