### ISSUE TITLE
How can I access that chromedriver installed in my app ?

### ISSUE THREAD

**Issue by Prime-Hritu** [heroku/heroku-buildpack-chrome-for-testing#8]
Isn't there any path specified in that chromedriver is installed ?

**Comment by mars** [comment]
After being installed by this buildpack ,`chromedriver` is already set on the `PATH` in dynos, accessible by calling `chromedriver`.

If you need the exact installation path, which may change in future versions of this buildpack, you can discover its location:
```bash
>>> heroku run bash --app my-app-name
$ which chromedriver
/app/.chrome-for-testing/chromedriver-linux64/chromedriver
```
